name: Publish NuGet

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Build and pack
        run: dotnet pack --configuration Release

      - name: Push to NuGet
        run: dotnet nuget push Shared/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
